-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "avgTimeOnPage" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "headerAltText" TEXT NOT NULL DEFAULT 'Header image',
ADD COLUMN     "views" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "weight" DOUBLE PRECISION NOT NULL DEFAULT 1;
